"""empty message

Revision ID: e6d13acc9922
Revises: a0d376ac3b29
Create Date: 2020-04-26 13:25:41.974860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d13acc9922'
down_revision = 'a0d376ac3b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('slug', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'project', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'slug')
    # ### end Alembic commands ###
